### ISSUE TITLE
验收待修复

### ISSUE THREAD

**Issue by huangjun12** [txyugood/PaddleMVF#1]
1. 推理只输出了分类结果，没有概率

2. TIPC训练完后保存的路径不对，导致无法导出推理模型并进行推理

**Comment by txyugood** [comment]
收到，稍后我改一下。

**Comment by huangjun12** [comment]
3. 提交精度相较于验收指标稍低一些，是有波动原因。建议再多跑几次实验，选用精度高的。这边可以先锁定冠军

**Comment by txyugood** [comment]
好的 那我再跑几次。

**Comment by Ligoml** [comment]
超参部分是可以调节的，为了避免争议我们需要在你的模型达到验收精度后宣布冠军，试验可以多跑几次：
![c9bac9cdc1dd4a5865baa586ea60048f](https://user-images.githubusercontent.com/39876205/147456608-f30554af-2df3-40f7-8af1-3c965093d3b5.png)

**Comment by txyugood** [comment]
好的正在跑

**Comment by txyugood** [comment]
1.推理脚本补充了概率输出。
2.TIPC补充了infer所需的example文件。
3.经过多次训练已达到论文中指标。
请验收，谢谢。

**Comment by huangjun12** [comment]
tipc部分在aistudio上仍然是无法运行的，麻烦再check下哈

**Comment by txyugood** [comment]
好的。我一直都是在本地测试的TIPC，我现在测一下AI Studio的。。

**Comment by txyugood** [comment]
@huangjun12 您好，已修复。AI Studio和github代码均已更新。麻烦在运行一下吧，谢谢！

**Comment by huangjun12** [comment]
可以将模型代码整理重构一下，提个pr到PaddleVideo中， https://github.com/PaddlePaddle/PaddleVideo

**Comment by txyugood** [comment]
好的，我研究一下，下一步进行这个工作。
